Fixes tests after upgrading expect
After upgrading expect to version 29.6.2 a test started failing with the below error. Switching to toBeInstanceOf for equivalent behavior.

```
  1) helper - loadUser()
       loadUser should return a promise:
     TypeError: _get__(...)(...).toBeA is not a function
```

See: https://github.com/jestjs/jest/issues/2990